name: Update README with Maven build and coverage

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean verify

    - name: Generate JaCoCo report
      run: mvn jacoco:report

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: target/site/jacoco/jacoco.xml

    - name: Update README
      run: |
        echo "Maven Build Status: ![Build Status](https://img.shields.io/badge/build-passing-brightgreen)" >> README.md
        echo "Coverage Status: [![Coverage Status](https://coveralls.io/repos/github/saraferraro18/PROVAASSIGNMENT"/badge.svg)](https://coveralls.io/github/saraferraro18/PROVAASSIGNMENT)" >> README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
